version: "3"

services:
  rt:
    build:
      context: .
    image: docker.io/firefart/requesttracker:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -connect localhost:9000 -bind || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 5
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./shredder/:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

  cron:
    build:
      context: .
    image: docker.io/firefart/requesttracker:latest
    restart: always
    # the cron daemon needs to run as root
    user: root
    command: ["/root/cron_entrypoint.sh"]
    # no need for tini here
    entrypoint: ""
    # disable the healthcheck from the main dockerfile
    healthcheck:
      disable: true
    depends_on:
      rt:
        condition: service_healthy
        restart: true
      # we send rt-mailgate over to nginx
      nginx:
        condition: service_healthy
        restart: true
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./crontab:/root/crontab:ro # needed so we can add it ro. Permissions are changed in startup script
      - ./cron/:/cron
      - ./shredder/:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

  nginx:
    build:
      context: nginx
    image: docker.io/firefart/requesttracker:nginx-latest
    ports:
      - "0.0.0.0:${PORT:-443}:443"
      - "127.0.0.1:8080:8080" # expose mailgate vhost to host
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9001/health || exit 1"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    depends_on:
      rt:
        condition: service_healthy
        restart: true
    volumes:
      - ./nginx/certs/:/certs/:ro
      - ./nginx/startup-scripts/:/docker-entrypoint.d/:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_rt
