services:
  rt:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 5
      endpoint_mode: vip
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./shredder/:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    # make the host available inside the image
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  cron:
    build:
      context: .
    image: firefart/requesttracker:latest
    restart: always
    # the cron daemon needs to run as root
    user: root
    command: ["/root/cron_entrypoint.sh"]
    # no need for tini here
    entrypoint: ""
    # disable the healthcheck from the main dockerfile
    healthcheck:
      disable: true
    depends_on:
      rt:
        condition: service_healthy
        restart: true
      # we send rt-mailgate over to caddy
      caddy:
        condition: service_healthy
        restart: true
    volumes:
      - ./RT_SiteConfig.pm:/opt/rt5/etc/RT_SiteConfig.pm:ro
      - ./msmtp/msmtp.conf:/etc/msmtprc:ro
      - ./msmtp/:/msmtp:ro
      - ./getmail/getmailrc:/getmail/getmailrc:ro
      - ./gpg/:/opt/rt5/var/data/gpg
      - ./smime/:/opt/rt5/var/data/smime
      - ./crontab:/root/crontab:ro # needed so we can add it ro. Permissions are changed in startup script
      - ./cron/:/cron
      - ./shredder/:/opt/rt5/var/data/RT-Shredder
      - /etc/localtime:/etc/localtime:ro
    # make the host available inside the image
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "0.0.0.0:443:443"
      - "127.0.0.1:8080:8080" # expose mailgate vhost to host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs/:/certs/:ro
      - /etc/localtime:/etc/localtime:ro
      - vol_caddy_data:/data
      - vol_caddy_config:/config
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "-q", "http://127.0.0.1:1337/"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      rt:
        condition: service_healthy
        restart: true
    networks:
      - net

volumes:
  vol_caddy_data:
  vol_caddy_config:

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_rt
