apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "request-tracker.rt.fullname" . }}
  labels:
    {{- include "request-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: rt
spec:
  {{- if not .Values.rt.autoscaling.enabled }}
  replicas: {{ .Values.rt.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "request-tracker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rt
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "request-tracker.labels" . | nindent 8 }}
        app.kubernetes.io/component: rt
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.rt.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "request-tracker.serviceAccountName" . }}
      {{- with .Values.rt.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.rt.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.rt.image.repository }}:{{ .Values.rt.image.tag }}"
          imagePullPolicy: {{ .Values.rt.image.pullPolicy }}
          ports:
            - name: rt-fcgi
              containerPort: {{ .Values.rt.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "REQUEST_METHOD=GET REQUEST_URI=/ SCRIPT_NAME=/ cgi-fcgi -connect localhost:{{ .Values.rt.port }} -bind || exit 1"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "REQUEST_METHOD=GET REQUEST_URI=/ SCRIPT_NAME=/ cgi-fcgi -connect localhost:{{ .Values.rt.port }} -bind || exit 1"
          {{- with .Values.rt.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.rt.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.rt.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
