{{- if .Values.rt.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rt
  labels:
    {{- include "request-tracker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rt
  minReplicas: {{ .Values.rt.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rt.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.rt.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.rt.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.rt.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.rt.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
