apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: db-init
        {{- with .Values.rt.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.rt.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.rt.image.repository }}:{{ .Values.rt.image.tag }}"
        imagePullPolicy: {{ .Values.rt.image.pullPolicy }}
        command: ["/opt/rt/sbin/rt-setup-database"]
        args: ["--action init", "--skip-create"]
        workingDir: /opt/rt
        volumeMounts:
          - name: rt-config
            mountPath: /opt/rt/etc/RT_SiteConfig.pm
            subPath: RT_SiteConfig.pm
            readOnly: true
          - name: rt-gpg
            mountPath: /opt/rt/var/data/gpg
            readOnly: false
          - name: rt-smime
            mountPath: /opt/rt/var/data/smime
            readOnly: true
      volumes:
        - name: rt-config
          configMap:
            name: rt-config
            items:
              - key: rtSiteConfig
                path: RT_SiteConfig.pm
        - name: rt-gpg
          persistentVolumeClaim:
            claimName: rt-gpg
        - name: rt-smime
          persistentVolumeClaim:
            claimName: rt-smime
