{{- range .Values.cronjobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ printf "%s-%s" (include "request-tracker.fullname" $) .name | trunc -63 | replace "_" "-" }}"
  labels:
    {{- include "request-tracker.labels" $ | nindent 4 }}
spec:
  schedule: "{{ .schedule }}"
  concurrencyPolicy: {{ .concurrencyPolicy | default "Forbid" }}
  timeZone: {{ .timeZone | default "UTC" }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "request-tracker.serviceAccountName" $ }}
          securityContext:
            {{- toYaml .podSecurityContext | default $.Values.rt.podSecurityContext | nindent 12 }}
          containers:
          - name: "{{ printf "%s-%s" (include "request-tracker.fullname" $) .name | trunc -63 | replace "_" "-" }}"
            securityContext:
              {{- toYaml (.securityContext | default $.Values.rt.securityContext) | nindent 14 }}
            image: "{{ .image.repository | default $.Values.rt.image.repository }}:{{ .image.tag | default $.Values.rt.image.tag }}"
            imagePullPolicy: {{ .image.pullPolicy | default $.Values.rt.image.pullPolicy }}
            command:
              {{- toYaml .command | nindent 14 }}
            {{- with .resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: rt-config
              mountPath: /opt/rt/etc/RT_SiteConfig.pm
              subPath: RT_SiteConfig.pm
              readOnly: true
            - name: msmtp-config
              mountPath: /msmtp/msmtp.conf
              subPath: msmtp.conf
              readOnly: true
            - name: getmailrc-config
              mountPath: /getmail/getmailrc
              subPath: getmailrc
              readOnly: true
            - name: rt-gpg
              mountPath: /opt/rt/var/data/gpg
              readOnly: false
            - name: rt-smime
              mountPath: /opt/rt/var/data/smime
              readOnly: true
            - name: rt-shredder
              mountPath: /opt/rt/var/data/RT-Shredder
              readOnly: false
            - name: rt-cron
              mountPath: /cron
              readOnly: false
          {{- with $.Values.rt.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
            - name: rt-config
              configMap:
                name: "{{ printf "%s-config" (include "request-tracker.fullname" $) | trunc -63 | replace "_" "-" }}"
                items:
                  - key: rtSiteConfig
                    path: RT_SiteConfig.pm
            - name: msmtp-config
              configMap:
                name: "{{ printf "%s-config" (include "request-tracker.fullname" $) | trunc -63 | replace "_" "-" }}"
                items:
                  - key: msmtp
                    path: msmtp.conf
            - name: getmailrc-config
              configMap:
                name: "{{ printf "%s-config" (include "request-tracker.fullname" $) | trunc -63 | replace "_" "-" }}"
                items:
                  - key: getmailrc
                    path: getmailrc
            - name: rt-gpg
              persistentVolumeClaim:
                claimName: {{ include "request-tracker.fullname" $ }}-gpg
            - name: rt-smime
              persistentVolumeClaim:
                claimName: {{ include "request-tracker.fullname" $ }}-smime
            - name: rt-shredder
              persistentVolumeClaim:
                claimName: {{ include "request-tracker.fullname" $ }}-shredder
            - name: rt-cron
              persistentVolumeClaim:
                claimName: {{ include "request-tracker.fullname" $ }}-cron
          {{- with $.Values.rt.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .restartPolicy | default "Never" }}
{{- end }}
