apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "request-tracker.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
