{{- if and .Values.db.create (not .Values.db.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: rt-db-creds
  labels:
    {{- include "request-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  dbname: {{ required "db.name is required when db.create is true" .Values.db.name | quote }}
  username: {{ required "db.username is required when db.create is true" .Values.db.username | quote }}
  password: {{ required "db.password is required when db.create is true" .Values.db.password | quote }}
{{- end }}
