{{- if not .Values.mail.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "request-tracker.mailSecretName" . }}
  labels:
    {{- include "request-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  msmtp: |-
{{ .Values.mail.msmtp | indent 4 }}
  getmailrc: |-
{{ .Values.mail.getmailrc | indent 4 }}
{{- end }}
