apiVersion: batch/v1
kind: Job
metadata:
  name: db-update-job
spec:
  ttlSecondsAfterFinished: 3600 # Clean up the job after 1 hour
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: generate-config
          image: "hairyhenderson/gomplate:stable-alpine"
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 65534 # nobody user
            runAsGroup: 65534 # nobody group
          command:
            - gomplate
            - -f
            - /templates/RT_SiteConfig.pm
            - -o
            - /output/RT_SiteConfig.pm
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: RT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rt-db-creds
                  key: dbname
            - name: RT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: rt-db-creds
                  key: username
            - name: RT_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rt-db-creds
                  key: password
          volumeMounts:
            - name: rt-config-template
              mountPath: /templates/RT_SiteConfig.pm
              subPath: RT_SiteConfig.pm
              readOnly: true
            - name: rt-config
              mountPath: /output
              readOnly: false
      containers:
        - name: db-update
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000 # the user id of the rt user in the container
            runAsGroup: 1000 # the group id of the rt user in the container
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          image: "firefart/requesttracker:latest" # adjest the tag as needed
          imagePullPolicy: "Always"
          command: ["/opt/rt/sbin/rt-setup-database"]
          args: ["--action", "upgrade", "--upgrade-from=4.4.2"] # adjust the version as needed
          workingDir: /opt/rt
          volumeMounts:
            - name: rt-config
              mountPath: /opt/rt/etc/RT_SiteConfig.pm
              subPath: RT_SiteConfig.pm
              readOnly: true
            - name: rt-gpg
              mountPath: /opt/rt/var/data/gpg
              readOnly: false
            - name: rt-smime
              mountPath: /opt/rt/var/data/smime
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: rt-config-template
          configMap:
            name: rt-config
            items:
              - key: rtSiteConfig
                path: RT_SiteConfig.pm
        - name: rt-config
          emptyDir: {}
        - name: rt-gpg
          persistentVolumeClaim:
            claimName: rt-gpg
        - name: rt-smime
          persistentVolumeClaim:
            claimName: rt-smime
        - name: tmp
          emptyDir: {}
