name: Build Docker Images

# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/docker.yml
      - cron_entrypoint.sh
  # only build without pushing on PRs
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/docker.yml
      - cron_entrypoint.sh
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

# only allow one build at a time per branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DO_PUSH: ${{ github.ref == 'refs/heads/main' }} # do not push on PRs
  REGISTRY_IMAGE: firefart/requesttracker

jobs:
  build:
    runs-on: ${{ matrix.builders.runner }}

    strategy:
      matrix:
        builders:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
        versions:
          - rt: "5.0.8"
            rtir: "5.0.8"
          - rt: "5.0.9"
            rtir: "5.0.8"
          - rt: "6.0.0"
            rtir: "5.0.8"
          - rt: "6.0.1"
            rtir: "6.0.1"
          - rt: "6.0.2"
            rtir: "6.0.1"

    steps:
      - name: checkout sources
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare
        run: |
          platform=${{ matrix.builders.platform }}
          rt=${{ matrix.versions.rt }}
          echo "ARTIFACT_NAME=${rt}-${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        if: env.DO_PUSH == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v7
        with:
          build-args: |
            RT_VERSION=${{ matrix.versions.rt }}
            RTIR_VERSION=${{ matrix.versions.rtir }}
          context: .
          file: Dockerfile
          platforms: ${{ matrix.builders.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          push: ${{ env.DO_PUSH }}
          sbom: true
          provenance: mode=max
          outputs: type=image,push-by-digest=true,name-canonical=true,push=${{ env.DO_PUSH }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-${{ env.ARTIFACT_NAME }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        versions:
          - rt: "5.0.8"
          - rt: "5.0.9"
            create_major: "true" # only enable on the latest version of a major
          - rt: "6.0.0"
          - rt: "6.0.1"
          - rt: "6.0.2"
            latest_tag: "true" # point the latest tag to this version
            create_major: "true" # only enable on the latest version of a major
    steps:
      - name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-${{ matrix.versions.rt }}-*
          merge-multiple: true

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        if: env.DO_PUSH == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          flavor: |
            # disable setting the latest tag by default
            latest=false
          tags: |
            # Enable latest tag if set
            type=raw,value=latest,enable=${{ matrix.versions.latest_tag == 'true' }}
            # Create a tag for the major version
            type=semver,pattern={{major}},value=${{ matrix.versions.rt }},enable=${{ matrix.versions.create_major == 'true' }}
            # Create a tag for the full version
            type=raw,value=${{ matrix.versions.rt }}
            type=schedule,pattern={{date 'YYYYMMDD'}},prefix=nightly-${{ matrix.versions.rt }}-

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
