name: yamllint
on:
  push:
    paths:
      - "**.yml"
      - "**.yaml"
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install yamllint
        run: pipx install yamllint
      - name: Lint YAML
        run: yamllint --strict --config-file .yamllint.yml .
